In [1]:
import torch
import numpy as np

In [2]:
print(torch.__version__)

1.7.1


In [3]:
device = "cuda" if torch.cuda.is_available() else "cpu"
my_tensor = torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32,device=device,
                        requires_grad=True)

C:\Users\rohit.pratapwar\Anaconda3\envs\tf\lib\site-packages\torch\cuda\__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  ..\c10\cuda\CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0


In [4]:
print(my_tensor)
print(my_tensor.dtype)
print(my_tensor.device)
print(my_tensor.shape)
print(my_tensor.requires_grad)

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)
torch.float32
cpu
torch.Size([2, 3])
True


In [5]:
x = torch.empty(size=(3,3))
print(x)
x = torch.zeros((3,3))
print(x)
x = torch.rand((3,3))
print(x)
x = torch.ones((3,3))
print(x)
x = torch.eye(3,3)
print(x)
x = torch.arange(start=0,end=5,step=1)
print(x)
x = torch.linspace(start=0.1,end=1,steps=10)
print(x)
x = torch.empty(size=(1,5)).normal_(mean=0,std=1)
print(x)
x = torch.empty(size=(1,5)).uniform_(0,1)
print(x)
x = torch.diag(torch.ones(3))
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.7935, 0.3345, 0.5754],
        [0.1576, 0.6435, 0.5214],
        [0.2617, 0.3697, 0.8905]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([0, 1, 2, 3, 4])
tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])
tensor([[ 0.9128, -0.3045,  0.7043,  0.5553,  0.1971]])
tensor([[0.7616, 0.8607, 0.5740, 0.7178, 0.6193]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [6]:
tensor = torch.arange(4)
print(tensor.bool())
print(tensor.short())
print(tensor.long())
print(tensor.half())
print(tensor.float())
print(tensor.double())

tensor([False,  True,  True,  True])
tensor([0, 1, 2, 3], dtype=torch.int16)
tensor([0, 1, 2, 3])
tensor([0., 1., 2., 3.], dtype=torch.float16)
tensor([0., 1., 2., 3.])
tensor([0., 1., 2., 3.], dtype=torch.float64)


In [7]:
np_array = np.zeros((5,5))
tensor = torch.from_numpy(np_array)
np_array_back = tensor.numpy()

In [8]:
x = torch.tensor([1,2,3])
y = torch.tensor([7,8,9])

In [9]:
z1 = torch.empty(3)
torch.add(x,y,out=z1)


tensor([ 8., 10., 12.])

In [10]:
z2 = torch.add(x,y)

In [11]:
z = x + y

In [12]:
z = x - y

In [13]:
z = torch.true_divide(x,y)
print(z)

tensor([0.1429, 0.2500, 0.3333])


In [14]:
# inplace operation
 
t = torch.zeros(3)
t.add_(x)

tensor([1., 2., 3.])

In [15]:
t += x

In [16]:
# expotentiations
z = x.pow(2)
print(z)
z = x ** 2
print(z)

tensor([1, 4, 9])
tensor([1, 4, 9])


In [17]:
z = x > 0
print(z)
z = x < 0
print(z)

tensor([True, True, True])
tensor([False, False, False])


In [18]:
#matrix multiplication

x1 = torch.rand((2,5))
x2 = torch.rand((5,3))
x3 = torch.mm(x1, x2)
print(x3)
x3 = x1.mm(x2)
print(x3)


tensor([[1.2375, 1.4345, 0.8020],
        [1.1274, 1.2775, 0.4944]])
tensor([[1.2375, 1.4345, 0.8020],
        [1.1274, 1.2775, 0.4944]])


In [19]:
# matrix expotentiation

matrix_exp = torch.rand(5,5)
print(matrix_exp.matrix_power(5))

tensor([[49.0411, 38.8877, 26.5969, 44.8657, 20.4492],
        [39.5776, 31.3971, 21.4773, 36.1610, 16.4961],
        [40.3367, 31.9828, 21.8721, 36.8821, 16.8159],
        [41.9326, 33.2963, 22.7552, 38.3274, 17.4734],
        [35.1170, 27.8555, 19.0521, 32.1045, 14.6352]])


In [20]:
# elementwise multiplication

z = x * y 
print(z)

tensor([ 7, 16, 27])


In [21]:
# dot product

z = torch.dot(x,y)
print(z)

tensor(50)


In [22]:
# batch matrix multiplication
batch = 32
n = 10
m = 20
p = 30

tensor1 = torch.rand(batch,n,m)
tensor2 = torch.rand(batch,m,p)

out_bmm = torch.bmm(tensor1,tensor2)
print(out_bmm)

tensor([[[5.8649, 4.0494, 4.9355,  ..., 4.4309, 4.8471, 5.8823],
         [4.9141, 3.9754, 4.6703,  ..., 4.5655, 4.6598, 6.2167],
         [6.7955, 4.3616, 5.5672,  ..., 4.9801, 5.3178, 7.0567],
         ...,
         [6.0339, 5.6921, 5.8235,  ..., 4.5514, 4.0425, 6.5693],
         [7.4556, 5.3560, 5.7531,  ..., 5.0402, 5.2281, 7.5037],
         [4.0085, 3.4488, 3.9066,  ..., 2.9943, 3.9372, 4.1775]],

        [[5.2536, 3.7245, 4.0080,  ..., 4.4861, 4.4154, 4.9116],
         [5.0887, 4.3905, 3.8977,  ..., 3.7635, 4.6832, 5.3946],
         [5.2965, 4.5958, 4.7878,  ..., 4.5754, 5.1701, 5.3495],
         ...,
         [5.0998, 4.7081, 4.4355,  ..., 4.9084, 4.2352, 5.2930],
         [5.2569, 4.0687, 3.9136,  ..., 4.0326, 4.3453, 4.6016],
         [5.6376, 3.9340, 4.4388,  ..., 5.0250, 5.0951, 5.3122]],

        [[7.0165, 7.6486, 5.6090,  ..., 4.7428, 5.9598, 7.2463],
         [4.4782, 5.7892, 4.1984,  ..., 4.0253, 3.9359, 5.0178],
         [4.6740, 5.0643, 3.9674,  ..., 3.4281, 4.3726, 5.

In [23]:
#broadcasting
x1 = torch.rand((5,5))
x2 = torch.rand((1,5))

In [24]:
z = x1-x2
z = x1 ** x2

In [25]:
# tensorflow operations

sum_x = torch.sum(x,dim=0)
values,indices = torch.max(x,dim=0)
values,indices = torch.min(x,dim=0)
abs_x = torch.abs(x)
z = torch.argmax(x,dim=0)
z = torch.argmin(x,dim=0)
mean_x = torch.mean(x.float(),dim=0)
z = torch.eq(x,y)
print(z)
sorted_y, indices = torch.sort(y,dim=0,descending=False)
z = torch.clamp(x, min=0)
print(z)

tensor([False, False, False])
tensor([1, 2, 3])


In [26]:
x = torch.tensor([1,0,1,1,1],dtype=torch.bool)
z = torch.any(x)
print(z)
z = torch.all(x)
print(z)

tensor(True)
tensor(False)


# Tensor Indexing

In [27]:
batch_size = 10
features = 25
x = torch.rand(batch_size,features)
print(x[0].shape) # x[0,:]
print(x[:,0].shape)
print(x[2,0:10])

torch.Size([25])
torch.Size([10])
tensor([0.0773, 0.8803, 0.4764, 0.7384, 0.8346, 0.4689, 0.9972, 0.1586, 0.4698,
        0.3396])


In [28]:
x [0,0] = 100

In [29]:
x = torch.arange(10)
indices = [2,5,8]
print(x[indices])

tensor([2, 5, 8])


In [30]:
x = torch.rand((3,5))
rows = torch.tensor([1,0])
cols = torch.tensor([4,0])
print(x[rows,cols].shape)

torch.Size([2])


In [31]:
# advanced indexing
x = torch.arange(10)
print(x[(x < 2) | (x > 8)])
print(x[(x < 2) & (x > 8)])
print(x[x.remainder(2) ==0])

tensor([0, 1, 9])
tensor([], dtype=torch.int64)
tensor([0, 2, 4, 6, 8])


In [32]:
# useful operations

print(torch.where(x > 5, x, x*2 ))
print(torch.tensor([0,0,1,2,2,3,4,]).unique())
print(x.ndimension())
print(x.numel())


tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])
tensor([0, 1, 2, 3, 4])
1
10


# Tensor Reshaping

In [33]:
x = torch.arange(9)

In [34]:
x_3x3 = x.view(3,3)
print(x_3x3)
print(x_3x3.shape)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
torch.Size([3, 3])


In [35]:
x_3x3 = x.reshape(3,3)
print(x_3x3.shape)

torch.Size([3, 3])


In [36]:
y = x_3x3.t()
y
print(y.contiguous().view(9))

tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])


In [37]:
x1 = torch.rand((2,5))
x2 = torch.rand((2,5))

print(torch.cat((x1,x2),dim=0).shape)
print(torch.cat((x1,x2),dim=1).shape)

z1 = x1.view(-1)
print(z1.shape)

torch.Size([4, 5])
torch.Size([2, 10])
torch.Size([10])


In [38]:
batch = 64
x = torch.rand((batch,2,5))
z = x.view(batch,-1)
print(z.shape)

z = x.permute(0, 2, 1)
print(z.shape)

torch.Size([64, 10])
torch.Size([64, 5, 2])


In [39]:
x = torch.arange(10)
print(x.unsqueeze(0).shape)
print(x.unsqueeze(1).shape)

torch.Size([1, 10])
torch.Size([10, 1])


In [40]:
x = torch.arange(10).unsqueeze(0).unsqueeze(1) #1x1x10
z = x.squeeze(1)
print(z.shape)

torch.Size([1, 10])
