In [1]:
import torch

In [2]:
torch.__version__

'1.7.1'

In [3]:
import numpy as np

In [4]:
lst = [3,4,5]
arr = np.array(lst)

In [6]:
arr.dtype

dtype('int32')

In [7]:
tensors = torch.from_numpy(arr)
tensors

tensor([3, 4, 5], dtype=torch.int32)

In [9]:
tensors[1:4]

tensor([4, 5], dtype=torch.int32)

In [11]:
tensors[2] = 100

In [12]:
tensors

tensor([  3,   4, 100], dtype=torch.int32)

In [14]:
torch_arr = torch.tensor(lst)
torch_arr

tensor([3, 4, 5])

In [16]:
torch_arr[2] = 120
print(torch_arr)
print(arr)

tensor([  3,   4, 120])
[  3   4 100]


In [18]:
torch.zeros(2,3,dtype=torch.float64)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [19]:
torch.ones(2,3,dtype=torch.float64)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [20]:
a = torch.tensor([3,4,5],dtype=torch.float)
b = torch.tensor([7,8,9],dtype=torch.float)

In [21]:
print(a+b)

tensor([10., 12., 14.])


In [22]:
torch.add(a,b)

tensor([10., 12., 14.])

In [23]:
c = torch.zeros(3)

In [25]:
torch.add(a,b,out=c)

tensor([10., 12., 14.])

In [26]:
torch.add(a,b).sum()

tensor(36.)

### dot product & Multi operations

In [27]:
x = torch.tensor([1,2,3],dtype=torch.float)
y= torch.tensor([3,4,5],dtype=torch.float)

In [28]:
x.mul(y)

tensor([ 3.,  8., 15.])

In [29]:
x.dot(y)

tensor(26.)

In [37]:
x = torch.tensor([[1,4,2],[1,5,5]],dtype=float)
y = torch.tensor([[4,5],[9,11],[6,7]],dtype=float)

In [38]:
torch.mm(x,y)

tensor([[52., 63.],
        [79., 95.]], dtype=torch.float64)

In [39]:
torch.matmul(x,y)

tensor([[52., 63.],
        [79., 95.]], dtype=torch.float64)

In [40]:
x@y

tensor([[52., 63.],
        [79., 95.]], dtype=torch.float64)